export { uploadImage } from "./image"
export { saveResource } from "./resources"
export { saveNews } from "./news"
export { dataPanel } from "./panel"
export {deleteUser, getUserById,listUsers, updateUser} from "./users"