export const mockPosts = [
  {
    id: crypto.randomUUID(),
    title: "¿Cómo subir evidencias en Sofia Plus?",
    content: "Estoy intentando subir un documento PDF como evidencia en Sofia Plus, pero me sale un error. ¿Alguien sabe qué puedo hacer?",
    author: "María García",
    authorAvatar: "/avatars/user1.png",
    date: "Hace 2 horas",
    likesCount: 12,
    commentsCount: 5,
    tags: ["SENA", "Sofia Plus", "Evidencias"],
  },
  {
    id: crypto.randomUUID(),
    title: "Problemas con la plataforma LMS del SENA",
    content: "Desde ayer no puedo acceder a la plataforma LMS. ¿Alguien más tiene este problema o sabe si hay mantenimiento programado?",
    author: "Juan Rodríguez",
    authorAvatar: "/avatars/user2.png",
    date: "Hace 5 horas",
    likesCount: 8,
    commentsCount: 10,
    tags: ["SENA", "LMS", "Acceso"],
  },
  {
    id: crypto.randomUUID(),
    title: "¿Cómo crear un repositorio en GitHub?",
    content: "Necesito crear un repositorio en GitHub para mi proyecto final del SENA. ¿Alguien me puede explicar paso a paso cómo hacerlo?",
    author: "Carlos Mendoza",
    authorAvatar: "/avatars/user3.png",
    date: "Hace 1 día",
    likesCount: 20,
    commentsCount: 15,
    tags: ["GitHub", "Repositorio", "Proyecto"],
  },
];