export const nivelesReputacion = [
  {
    id: 1,
    nombre: "Principiante",
    color: "bg-gray-400",
    puntosMinimos: 0,
    image: "/principiante.svg",
    imageAlt: "Nivel de principiante",
  },
  {
    id: 2,
    nombre: "Aprendiz",
    color: "bg-yellow-500",
    puntosMinimos: 10,
    image: "/aprendiz.svg",
    imageAlt: "Nivel de aprendiz",
  },
  {
    id: 3,
    nombre: "Intermedio",
    color: "bg-blue-500",
    puntosMinimos: 30,
    image: "/intermedio.svg",
    imageAlt: "Nivel de intermedio",
  },
  {
    id: 4,
    nombre: "Avanzado",
    color: "bg-green-500",
    puntosMinimos: 60,
    image: "/avanzado.svg",
    imageAlt: "Nivel de avanzado",
  },
  {
    id: 5,
    nombre: "Experto",
    color: "bg-purple-600",
    puntosMinimos: 100,
    image: "/experto.svg",
    imageAlt: "Nivel de experto",
  },
  {
    id: 6,
    nombre: "Maestro",
    color: "bg-purple-600",
    puntosMinimos: 200,
    image: "/maestro.svg",
    imageAlt: "Nivel de maestro",
  },
];
